### ISSUE TITLE
npm run dev crashes on book.feelpp.org

### ISSUE THREAD

**Issue by prudhomm** [feelpp/antora-ui#27]
<@U050XH4JH5K> `npm run dev` (<http://book.feelpp.org|book.feelpp.org>) crash actuellement avec la v0.4:
```    source: /Users/prudhomm/Devel/book.feelpp.org (branch: develop &lt;worktree&gt; | start path: docs/user)
[22:36:05.354] FATAL (antora): Cannot read properties of undefined (reading 'version') in UI template partials/header-content.hbs
    Cause: Error
    n')
        at module.exports (helpers/get-install-page.js:10:50)
        at Object.wrapper (/Users/prudhomm/Devel/book.feelpp.org/node_modules/handlebars/dist/cjs/handlebars/internal/wrapHelper.js:15:19)
        at Object.eval [as main] (eval at createFunctionContext (/Users/prudhomm/Devel/book.feelpp.org/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), &lt;anonymous&gt;:35:169)
        at main (/Users/prudhomm/Devel/book.feelpp.org/node_modules/handlebars/dist/cjs/handlebars/runtime.js:208:32)
        at Object.ret (/Users/prudhomm/Devel/book.feelpp.org/node_modules/handlebars/dist/cjs/handlebars/runtime.js:212:12)
        at Object.ret [as header-content] (/Users/prudhomm/Devel/book.feelpp.org/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:519:21)
        at Object.invokePartialWrapper [as invokePartial] (/Users/prudhomm/Devel/book.feelpp.org/node_modules/handlebars/dist/cjs/handlebars/runtime.js:88:46)
        at Object.eval [as main] (eval at createFunctionContext (/Users/prudhomm/Devel/book.feelpp.org/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), &lt;anonymous&gt;:11:28)
        at main (/Users/prudhomm/Devel/book.feelpp.org/node_modules/handlebars/dist/cjs/handlebars/runtime.js:208:32)
        at Object.ret (/Users/prudhomm/Devel/book.feelpp.org/node_modules/handlebars/dist/cjs/handlebars/runtime.js:212:12)```

[Slack Message](https://feelpp.slack.com/archives/C050XHCSA77/p1682109429537839)

**Comment by ggrossetie** [comment]
The logic to get the latest stable version is a bit odd. It will be better once we will use `prerelease`.
For now, I will consider that we don't have a stable version if the content catalog contains only one version.
